CREATE TABLE desenvolvedora (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE,
    pais VARCHAR(100) NOT NULL,
    data_fundacao DATE NOT NULL
);

CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(254) NOT NULL UNIQUE,
    senha_hash VARCHAR(100) NOT NULL,
    papel VARCHAR(16) NOT NULL CHECK (papel IN ('USER', 'ADMIN')),
    data_cadastro TIMESTAMPTZ NOT NULL
);

CREATE TABLE jogo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(160) NOT NULL,
    descricao TEXT NOT NULL,
    preco NUMERIC(12, 2) NOT NULL CHECK (preco >= 0),
    data_lancamento DATE NOT NULL,
    desenvolvedora_id BIGINT NOT NULL REFERENCES desenvolvedora(id) ON DELETE RESTRICT
);

CREATE TABLE jogo_categoria (
    jogo_id BIGINT NOT NULL REFERENCES jogo(id) ON DELETE RESTRICT,
    categoria_id BIGINT NOT NULL REFERENCES categoria(id) ON DELETE RESTRICT,
    PRIMARY KEY (jogo_id, categoria_id)
);

CREATE TABLE conquista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jogo_id BIGINT NOT NULL REFERENCES jogo(id) ON DELETE RESTRICT,
    nome VARCHAR(120) NOT NULL,
    descricao TEXT NOT NULL
);

CREATE TABLE biblioteca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    jogo_id BIGINT NOT NULL REFERENCES jogo(id) ON DELETE RESTRICT,
    data_aquisicao TIMESTAMPTZ NOT NULL,
    preco_pago NUMERIC(12, 2) NOT NULL CHECK (preco_pago >= 0),
    horas_jogadas INTEGER NOT NULL DEFAULT 0 CHECK (horas_jogadas >= 0),
    CONSTRAINT uq_biblioteca_usuario_jogo UNIQUE (usuario_id, jogo_id)
);

CREATE TABLE avaliacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jogo_id BIGINT NOT NULL REFERENCES jogo(id) ON DELETE RESTRICT,
    usuario_id BIGINT NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    nota SMALLINT NOT NULL CHECK (nota BETWEEN 1 AND 5),
    comentario TEXT,
    data_avaliacao TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_avaliacao_usuario_jogo UNIQUE (usuario_id, jogo_id)
);

CREATE TABLE usuario_conquista (
    usuario_id BIGINT NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
    conquista_id BIGINT NOT NULL REFERENCES conquista(id) ON DELETE RESTRICT,
    data_desbloqueio TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (usuario_id, conquista_id)
);

CREATE INDEX idx_jogo_desenvolvedora_id ON jogo (desenvolvedora_id);
CREATE INDEX idx_jogo_categoria_categoria_id ON jogo_categoria (categoria_id);
CREATE INDEX idx_conquista_jogo_id ON conquista (jogo_id);
CREATE INDEX idx_biblioteca_jogo_id ON biblioteca (jogo_id);
CREATE INDEX idx_avaliacao_jogo_id ON avaliacao (jogo_id);
CREATE INDEX idx_usuario_conquista_conquista_id ON usuario_conquista (conquista_id);
